# Generated by Django 5.0.1 on 2024-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_desafio_flashcarddesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='flashcards',
            field=models.ManyToManyField(to='flashcard.flashcarddesafio'),
        ),
    ]
